/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveySurveyIdRouteImport } from './routes/survey.$surveyId'
import { Route as SurveySurveyIdIndexRouteImport } from './routes/survey.$surveyId.index'
import { Route as SurveySurveyIdAnalyticsRouteImport } from './routes/survey.$surveyId.analytics'
import { Route as SurveySurveyIdAreasRouteImport } from './routes/survey.$surveyId.areas'
import { Route as SurveySurveyIdDashboardRouteImport } from './routes/survey.$surveyId.dashboard'
import { Route as SurveySurveyIdDataRouteImport } from './routes/survey.$surveyId.data'
import { Route as SurveySurveyIdPlantsRouteImport } from './routes/survey.$surveyId.plants'
import { Route as SurveySurveyIdRecordsRouteImport } from './routes/survey.$surveyId.records'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveySurveyIdRoute = SurveySurveyIdRouteImport.update({
  id: '/survey/$surveyId',
  path: '/survey/$surveyId',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveySurveyIdIndexRoute = SurveySurveyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SurveySurveyIdRoute,
} as any)
const SurveySurveyIdAnalyticsRoute = SurveySurveyIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SurveySurveyIdRoute,
} as any)
const SurveySurveyIdAreasRoute = SurveySurveyIdAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => SurveySurveyIdRoute,
} as any)
const SurveySurveyIdDashboardRoute = SurveySurveyIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SurveySurveyIdRoute,
} as any)
const SurveySurveyIdDataRoute = SurveySurveyIdDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SurveySurveyIdRoute,
} as any)
const SurveySurveyIdPlantsRoute = SurveySurveyIdPlantsRouteImport.update({
  id: '/plants',
  path: '/plants',
  getParentRoute: () => SurveySurveyIdRoute,
} as any)
const SurveySurveyIdRecordsRoute = SurveySurveyIdRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => SurveySurveyIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/survey/$surveyId': typeof SurveySurveyIdRouteWithChildren
  '/survey/$surveyId/analytics': typeof SurveySurveyIdAnalyticsRoute
  '/survey/$surveyId/areas': typeof SurveySurveyIdAreasRoute
  '/survey/$surveyId/dashboard': typeof SurveySurveyIdDashboardRoute
  '/survey/$surveyId/data': typeof SurveySurveyIdDataRoute
  '/survey/$surveyId/plants': typeof SurveySurveyIdPlantsRoute
  '/survey/$surveyId/records': typeof SurveySurveyIdRecordsRoute
  '/survey/$surveyId/': typeof SurveySurveyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/survey/$surveyId/analytics': typeof SurveySurveyIdAnalyticsRoute
  '/survey/$surveyId/areas': typeof SurveySurveyIdAreasRoute
  '/survey/$surveyId/dashboard': typeof SurveySurveyIdDashboardRoute
  '/survey/$surveyId/data': typeof SurveySurveyIdDataRoute
  '/survey/$surveyId/plants': typeof SurveySurveyIdPlantsRoute
  '/survey/$surveyId/records': typeof SurveySurveyIdRecordsRoute
  '/survey/$surveyId': typeof SurveySurveyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/survey/$surveyId': typeof SurveySurveyIdRouteWithChildren
  '/survey/$surveyId/analytics': typeof SurveySurveyIdAnalyticsRoute
  '/survey/$surveyId/areas': typeof SurveySurveyIdAreasRoute
  '/survey/$surveyId/dashboard': typeof SurveySurveyIdDashboardRoute
  '/survey/$surveyId/data': typeof SurveySurveyIdDataRoute
  '/survey/$surveyId/plants': typeof SurveySurveyIdPlantsRoute
  '/survey/$surveyId/records': typeof SurveySurveyIdRecordsRoute
  '/survey/$surveyId/': typeof SurveySurveyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/survey/$surveyId'
    | '/survey/$surveyId/analytics'
    | '/survey/$surveyId/areas'
    | '/survey/$surveyId/dashboard'
    | '/survey/$surveyId/data'
    | '/survey/$surveyId/plants'
    | '/survey/$surveyId/records'
    | '/survey/$surveyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/survey/$surveyId/analytics'
    | '/survey/$surveyId/areas'
    | '/survey/$surveyId/dashboard'
    | '/survey/$surveyId/data'
    | '/survey/$surveyId/plants'
    | '/survey/$surveyId/records'
    | '/survey/$surveyId'
  id:
    | '__root__'
    | '/'
    | '/survey/$surveyId'
    | '/survey/$surveyId/analytics'
    | '/survey/$surveyId/areas'
    | '/survey/$surveyId/dashboard'
    | '/survey/$surveyId/data'
    | '/survey/$surveyId/plants'
    | '/survey/$surveyId/records'
    | '/survey/$surveyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SurveySurveyIdRoute: typeof SurveySurveyIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/$surveyId': {
      id: '/survey/$surveyId'
      path: '/survey/$surveyId'
      fullPath: '/survey/$surveyId'
      preLoaderRoute: typeof SurveySurveyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/$surveyId/': {
      id: '/survey/$surveyId/'
      path: '/'
      fullPath: '/survey/$surveyId/'
      preLoaderRoute: typeof SurveySurveyIdIndexRouteImport
      parentRoute: typeof SurveySurveyIdRoute
    }
    '/survey/$surveyId/analytics': {
      id: '/survey/$surveyId/analytics'
      path: '/analytics'
      fullPath: '/survey/$surveyId/analytics'
      preLoaderRoute: typeof SurveySurveyIdAnalyticsRouteImport
      parentRoute: typeof SurveySurveyIdRoute
    }
    '/survey/$surveyId/areas': {
      id: '/survey/$surveyId/areas'
      path: '/areas'
      fullPath: '/survey/$surveyId/areas'
      preLoaderRoute: typeof SurveySurveyIdAreasRouteImport
      parentRoute: typeof SurveySurveyIdRoute
    }
    '/survey/$surveyId/dashboard': {
      id: '/survey/$surveyId/dashboard'
      path: '/dashboard'
      fullPath: '/survey/$surveyId/dashboard'
      preLoaderRoute: typeof SurveySurveyIdDashboardRouteImport
      parentRoute: typeof SurveySurveyIdRoute
    }
    '/survey/$surveyId/data': {
      id: '/survey/$surveyId/data'
      path: '/data'
      fullPath: '/survey/$surveyId/data'
      preLoaderRoute: typeof SurveySurveyIdDataRouteImport
      parentRoute: typeof SurveySurveyIdRoute
    }
    '/survey/$surveyId/plants': {
      id: '/survey/$surveyId/plants'
      path: '/plants'
      fullPath: '/survey/$surveyId/plants'
      preLoaderRoute: typeof SurveySurveyIdPlantsRouteImport
      parentRoute: typeof SurveySurveyIdRoute
    }
    '/survey/$surveyId/records': {
      id: '/survey/$surveyId/records'
      path: '/records'
      fullPath: '/survey/$surveyId/records'
      preLoaderRoute: typeof SurveySurveyIdRecordsRouteImport
      parentRoute: typeof SurveySurveyIdRoute
    }
  }
}

interface SurveySurveyIdRouteChildren {
  SurveySurveyIdAnalyticsRoute: typeof SurveySurveyIdAnalyticsRoute
  SurveySurveyIdAreasRoute: typeof SurveySurveyIdAreasRoute
  SurveySurveyIdDashboardRoute: typeof SurveySurveyIdDashboardRoute
  SurveySurveyIdDataRoute: typeof SurveySurveyIdDataRoute
  SurveySurveyIdPlantsRoute: typeof SurveySurveyIdPlantsRoute
  SurveySurveyIdRecordsRoute: typeof SurveySurveyIdRecordsRoute
  SurveySurveyIdIndexRoute: typeof SurveySurveyIdIndexRoute
}

const SurveySurveyIdRouteChildren: SurveySurveyIdRouteChildren = {
  SurveySurveyIdAnalyticsRoute: SurveySurveyIdAnalyticsRoute,
  SurveySurveyIdAreasRoute: SurveySurveyIdAreasRoute,
  SurveySurveyIdDashboardRoute: SurveySurveyIdDashboardRoute,
  SurveySurveyIdDataRoute: SurveySurveyIdDataRoute,
  SurveySurveyIdPlantsRoute: SurveySurveyIdPlantsRoute,
  SurveySurveyIdRecordsRoute: SurveySurveyIdRecordsRoute,
  SurveySurveyIdIndexRoute: SurveySurveyIdIndexRoute,
}

const SurveySurveyIdRouteWithChildren = SurveySurveyIdRoute._addFileChildren(
  SurveySurveyIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SurveySurveyIdRoute: SurveySurveyIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
